// 1. positive & negative numbers.
let number = -2;

if(number>1) {console.log("this number is positive")
}else{console.log("this number is negative")
}

// 2.n check eligible for vote.
let age = 18;

if(age>=18){console.log("Eligible  for vote")

} else{console.log("Not eligible for vote")
}

// 3.checks number is even or odd. 

let num = 8;

if(num%2==0){
    console.log("Even Number");
}else{
    console.log("Odd Number");
}

//5. divisble by 5

let Number =15;

if(Number%5==0){console.log("divided by 5")
}else{console.log("not divided by 5")
}


//6.password 

let password = 34565;

if(password ==12345){console.log("access granted")
}else{console.log("access denied")
}

//7.leap year or not

let Days = 365;

if(Days==366){console.log("A leap year")
}else{console.log("Not leap year")

}


//8.check the number between 10-50

let NUMber = 50;
if( NUMber>=10 & NUMber<=50){console.log("number is between 10 to 50")  
}else{console.log("not between 10 to 50")
}

//4.greatest of two numbers

 
let num1 = 34;
let num2 = 27;

if(num1>num2){console.log("num1 is greatest THAN num2")
}else if(num2>num1){console.log("num2 is greatest than num2")
}else{console.log("both nums are equal")
}

// 9. divsible by 3 and 5

let numb = 15;

if(numb%3==0 & numb%5==0){console.log("it isFIZZBUZZ")
}else if (numb%3==0){console.log("it is fizz")
}else if (numb%5==0) {console.log("it is buzz")  
}

// 10. weekday or weekend

let numbe = 3;

if(numbe>=1,numbe<=5){console.log("that is weekday")
}else if (numbe>=6,numbe<=7){console.log("that is weeend")
}

//11.scorecard

 let score = 55;

 if(score>=90){console.log("grade A")
 }else if (score>=80){console.log("grade B")
}else if (score>=70){console.log("grade C")
}else if (score>=60){console.log("grade D")}
 else  {console.log("grade F") 
} 

//12.temperature

let temp =18;

if(temp>=30){console.log("it is HOT")
} else if (temp>=20){console.log("it is WARM")
} else{console.log("it is cold")}

//13.smallest of threee numbers

let numb1=65;
let numb2=78;
let numb3=90;

if(numb1<=numb2,numb1<=numb3){console.log("numb1 is smallest")
} else if ( nummb2<=numb1,numb2<=numb3){console.log("numb2 is smallest")
}else {console.log("numb3 is smallest") }

//14.MULTIPLE OF 4 & 6

let NUMB1 = 12;

if(NUMB1%4==0,NUMB1%6==0){console.log("it is multiple of 4 & 6")
} else{console.log("is not multiple of 4 & 6")}

// 15.vomels & consonant

let Character = "q";

if( Character  === 'a' || Character === 'e' || Character === 'i' || Character === 'o' || Character === 'u' ||
    Character === 'A' || Character === 'E' || Character === 'I' || Character === 'O' || Character === 'U')  {console.log("it is vowels")
} else{console.log("it is consonant") 
}
// 16.Eligble to apply

let AGE = 20;
let country = "china";

if(AGE >=18 && country == "INDIA" ){console.log("ELIGBLE TO apply")
}else{console.log("NOT ELIGBLE TO APPLY") 
}

//17. ! cannot question

let age2 = 2;

if (!(age2>=18)){
    console.log("You can not vote")
}else{
    console.log("You can vote")
}

//17. 

let num3 = -10;
let num4 = 65;

if(num3>0 && num4<100){console.log("number is lie between 0 to 100")
}else{console.log("number is  not lie between 0 to 100")}

//18.divisible by 3 & 7

let num6 = 2;
let  num7 = 2;

if(num6%3==0 || num7%7==0){console.log("divisible by 3 & 7")
}else{console.log("not dividible by 3 & 7")
}

// 19. login sucessful

let username = "admin";
let PASSWORD = 12345;

if(username=="admin" && PASSWORD==12345){console.log("login sucessfull")
}else{console.log("error")}

// 20. allow entry
let ID ="yes";
let ticket ="yes";

if(ID=="yes" && ticket=="yes"){console.log("allow entry")
}else{console.log("not allow") 
}


// 21.pass fail


let maths = 45;
let english = 32;
let hindi = 30;

if(maths<33 || english<33 || hindi<33 ) {console.log("fail")
} else{console.log("pass")}


// 22.
let NUMBER3 = 60;

if(!(NUMBER3 ==100)){console.log(" not equal to 100")
}else {console.log("equal to 100")
}

// 23.

  let CONTINUE = "no";

 if(!( CONTINUE == "yes")){console.log( "program exited")
}else{console.log("IN program")}

//24.

let AGE1 = 21;

if(!(AGE1<18)){console.log("not a minor")
}else{console.log("minor")}

//25.

let NUMBER2 =65;

if( NUMBER2>=10 && NUMBER2<=100 && NUMBER2!== 50){console.log("TRUE")
}else {console.log("FALSE")}